

import type { SVGProps } from 'react';

type IconProps = SVGProps<SVGSVGElement>;

export const Icons = {
  search: (props: IconProps) => (
      <svg
            xmlns="http://www.w3.org/2000/svg"
                  width="24"
                        height="24"
                              viewBox="0 0 24 24"
                                    fill="none"
                                          stroke="currentColor"
                                                strokeWidth="2"
                                                      strokeLinecap="round"
                                                            strokeLinejoin="round"
                                                                  {...props}
                                                                      >
                                                                            <circle cx="11" cy="11" r="8" />
                                                                                  <line x1="21" y1="21" x2="16.65" y2="16.65" />
                                                                                      </svg>
                                                                                        ),
  user: (props: IconProps) => (
                                                                                              <svg
                                                                                                    xmlns="http://www.w3.org/2000/svg"
                                                                                                          width="24"
                                                                                                                height="24"
                                                                                                                      viewBox="0 0 24 24"
                                                                                                                            fill="none"
                                                                                                                                  stroke="currentColor"
                                                                                                                                        strokeWidth="2"
                                                                                                                                              strokeLinecap="round"
                                                                                                                                                    strokeLinejoin="round"
                                                                                                                                                          {...props}
                                                                                                                                                              >
                                                                                                                                                                    <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                                                                                                                                                                    <circle cx="12" cy="7" r="4" />
                                                                                                                                                              </svg>
                                                                                                                                                                ),
  shoppingCart: (props: IconProps) => (
                                                                                                                                                                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.16"/></svg>
                                                                                                                                                                ),
  menu: (props: IconProps) => (
                                                                                                                                                                                      <svg
                                                                                                                                                                                            xmlns="http://www.w3.org/2000/svg"
                                                                                                                                                                                                  width="24"
                                                                                                                                                                                                        height="24"
                                                                                                                                                                                                              viewBox="0 0 24 24"
                                                                                                                                                                                                                    fill="none"
                                                                                                                                                                                                                          stroke="currentColor"
                                                                                                                                                                                                                                strokeWidth="2"
                                                                                                                                                                                                                                      strokeLinecap="round"
                                                                                                                                                                                                                                            strokeLinejoin="round"
                                                                                                                                                                                                                                                  {...props}
                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                            <line x1="4" y1="12" x2="20" y2="12" />
                                                                                                                                                                                                                                                                  <line x1="4" y1="6" x2="20" y2="6" />
                                                                                                                                                                                                                                                                        <line x1="4" y1="18" x2="20" y2="18" />
                                                                                                                                                                                                                                                                            </svg>
                                                                                                                                                                                                                                                                              ),
  twitter: (props: IconProps) => (
                                                                                                                                                                                                                                                                                    <svg
                                                                                                                                                                                                                                                                                          {...props}
                                                                                                                                                                                                                                                                                                viewBox="0 0 1200 1227"
                                                                                                                                                                                                                                                                                                      xmlns="http://www.w3.org/2000/svg"
                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                <path
                                                                                                                                                                                                                                                                                                                        d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z"
                                                                                                                                                                                                                                                                                                                                fill="currentColor"
                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                          </svg>
                                                                                                                                                                                                                                                                                                                                            ),
  arrow: (props: IconProps) => (<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>),
  plus: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14"/><path d="M12 5v14"/></svg>
                                                                                                                                                                                                                                                                                                                                               ),
  minus: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14"/></svg>
                                                                                                                                                                                                                                                                                                                                                       ),
  trash: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><line x1="10" x2="10" y1="11" y2="17"/><line x1="14" x2="14" y1="11" y2="17"/></svg>
                                                                                                                                                                                                                                                                                                                                                               ),
  heart: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>
                                                                                                                                                                                                                                                                                                                                                                       ),
  star: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>
                                                                                                                                                                                                                                                                                                                                                                               ),
  arrowRight: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                        ),
  chevronRight: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m9 18 6-6-6-6"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                ),
  lightbulb: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"/><path d="M9 18h6"/><path d="M10 22h4"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                         ),
  lamp: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M8 2h8l4 10H4L8 2Z"/><path d="M12 12v6"/><path d="M8 22v-2h8v2"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                  ),
  lampCeiling: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2v5"/><path d="M6 7h12l4 9H2l4-9Z"/><path d="M9.17 16a3 3 0 1 0 5.66 0"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                          ),
  lampWallUp: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M11 4h6l3 7H8l3-7Z"/><path d="M14 11v5a2 2 0 0 1-2 2H8"/><path d="M4 15h2a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2H4v-6Z"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
  loader: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                           ),
  facebook: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
  instagram: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                           <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                             ),
  tiktok: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <svg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         xmlns="http://www.w3.org/2000/svg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               viewBox="0 0 288 512"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {...props}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       fill="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               d="M288 152.2v50.93c-49.33-2.22-87-34.42-87-73.43 0-41.21 34.42-78.33 87-80.54V0C190.2.73 151.8 33.38 116.8 34.42 50.31 36.31 0 91.23 0 161.8c0 99.89 80.69 176.4 176.4 176.4 78.34 0 120.1-53.13 120.1-120.1-.81-8.82-1.9-17.4-3.5-25.9z"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ),
  instagramFeed: (props: IconProps) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
  share: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" x2="12" y1="2" y2="15"/></svg>
  ),
  copy: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
  ),
  close: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
  ),
  mail: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
  ),
  whatsapp: (props: IconProps) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M12.04 2c-5.46 0-9.91 4.45-9.91 9.91 0 1.75.46 3.45 1.32 4.95L2 22l5.25-1.38c1.45.79 3.08 1.21 4.79 1.21 5.46 0 9.91-4.45 9.91-9.91S17.5 2 12.04 2z" />
      <path d="M16.51 13.66c-.27-.14-1.59-.78-1.84-.87s-.43-.14-.61.14-.69.87-.85 1.04-.31.2-.58.07-.95-.36-1.81-1.12-1.42-1.25-1.59-1.47-.02-.34.12-.45.27-.31.4-.51.18-.27.27-.45.04-.33-.02-.47s-.61-1.47-.83-2.01-.44-.46-.61-.46-.36 0-.54 0-.43.07-.66.36-.89.87-.89 2.13s.92 2.47 1.04 2.64.95 1.5 2.31 2.05c1.36.55 1.81.7 2.14.89.48.28.91.23 1.25.14.39-.1.87-.36 1-.7.13-.34.13-.65.09-.79s-.14-.23-.27-.37z" />
    </svg>
  ),
  sun: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>
  ),
  radio: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4.9 19.1C1 15.2 1 8.8 4.9 4.9"/><path d="M7.8 16.2c-2.1-2.1-2.1-5.6 0-7.8"/><circle cx="12" cy="12" r="2"/><path d="M16.2 7.8c2.1 2.1 2.1 5.6 0 7.8"/><path d="M19.1 4.9C23 8.8 23 15.2 19.1 19.1"/></svg>
  ),
  toggleRight: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="20" height="12" x="2" y="6" rx="6" ry="6"/><circle cx="16" cy="12" r="2"/></svg>
  ),
  fan: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M10.12 4.01a1.5 1.5 0 0 0-2.24 0L3.33 8.56A1.5 1.5 0 0 0 4.4 11h15.2a1.5 1.5 0 0 0 1.07-2.44Z"/><path d="M13.88 19.99a1.5 1.5 0 0 0 2.24 0l4.55-4.55a1.5 1.5 0 0 0-1.07-2.44H4.4a1.5 1.5 0 0 0-1.07 2.44Z"/><path d="M12 12v.01"/></svg>
  ),
  play: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  ),
  pause: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <rect x="6" y="4" width="4" height="16" />
      <rect x="14" y="4" width="4" height="16" />
    </svg>
  ),
  wrench: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" {...props}><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>
  ),
  download: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" {...props}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>
  ),
};

    